name: Build site and publish

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Jekyll
      uses: gha-utilities/jekyll-build@v0.0.2
      with:
        destination: _site
    - name: Publish to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        BRANCH: test-deploy # The branch the action should deploy to.
        FOLDER: _site # The folder the action should deploy.
